### PR TITLE
Dev mode

### PR DESCRIPTION
**Pull request by evelinec**
Converted guide to run in dev mode.

- Updated the inconsistent formatting, ie, 2 vs 4 spacing

### CODE REVIEW

**Comment by evelinec** [comment]
> * **Injecting static configuration**
>   
>   * [ ]  suggest `microprofile` hotspot to highlight the whole `<dependency>...</dependency>` block instead of `<artifactId>...</artifactId>`
> * **Adding configuration to the microservice**
>   
>   * [ ]  2 `config_ordinal` hotspots not highlight
>   * [ ]  `150` hotspot not highlight
>   * [ ]  `100` hotspot not highlight
>   * [ ]  `resources/CustomConfigSource.json` hotspot not focus to the file
>   * [ ]  `io_openliberty_guides_inventory_inMaintenance` hotspot not highlight
> * **Testing the application**
>   
>   * [ ]  The ConfigurationIT.java on the right pane, the "ERROR: ..." lines and "private final String INV_MAINTENANCE_PROP..." line are not formated properly
>   * [ ]  If the test order is important, use junit5 way and update the test output, see https://github.com/OpenLiberty/guide-cdi-intro/blob/master/finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
> * [ ]  In SystemClient.java, `import javax.enterprise.context.Dependent;` no need

Except the `Testing the application` section, the others weren't changed in this PR. Can you create separate issue for those?

**Comment by evelinec** [comment]
Addressed review feedback for changes in this PR. Other hotspot suggestion is in #113. @gkwan-ibm Can you review again? Thanks.

**Comment by gkwan-ibm** [comment]
>     * **Injecting static configuration**
>       * [ ]  suggest `microprofile` hotspot to highlight the whole `<dependency>...</dependency>` block instead of `<artifactId>...</artifactId>`
> 
>     * **Adding configuration to the microservice**
>       * [ ]  2 `config_ordinal` hotspots not highlight
>       * [ ]  `150` hotspot not highlight
>       * [ ]  `100` hotspot not highlight
>       * [ ]  `resources/CustomConfigSource.json` hotspot not focus to the file
>       * [ ]  `io_openliberty_guides_inventory_inMaintenance` hotspot not highlight

Although the original/existing master does not do the above, I think we can improve them.

**Comment by gkwan-ibm** [comment]
dev content reviewed

**Comment by NimG98** [comment]
## Testing the application
- [ ] This sentence doesn't apply, because when you change the values in `resources/CustomConfigSource.json` and then run the tests, the tests don't fail.
    > Then manually change some configuration values in the `resources/CustomConfigSource.json` file. Rerun the tests. You will see a test failure occur.
- [ ] add hotspots for `io_openliberty_guides_inventory_inMaintenance` and `META-INF/microprofile-config.properties`:
    > The `testInitialServiceStatus()` test case reads the value of the `io_openliberty_guides_inventory_inMaintenance` configuration property in the file `META-INF/microprofile-config.properties`
    > Because the `io_openliberty_guides_inventory_inMaintenance` configuration property is set to false by default

**Comment by NimG98** [comment]
## Testing the application
- [ ] add hotspot for which configuration line to delete:
    > To see whether the tests detect a failure, remove the configuration resetting line in the `setup()` method 
- [ ] add hotspots for `io_openliberty_guides_inventory_inMaintenance` and `META-INF/microprofile-config.properties`:
    > The `testInitialServiceStatus()` test case reads the value of the `io_openliberty_guides_inventory_inMaintenance` configuration property in the file `META-INF/microprofile-config.properties`
    > Because the `io_openliberty_guides_inventory_inMaintenance` configuration property is set to false by default

**Comment by NimG98** [comment]
- [ ] On linux, the tests fail in this scenario (which it shouldn't):
    - when you manually change some configuration values in the `resources/CustomConfigSource.json`
(e.g. change `"io_openliberty_guides_inventory_inMaintenance":false` to `"io_openliberty_guides_inventory_inMaintenance":true`) 
WITHOUT removing the configuration resetting line in the `setup()` method of the `ConfigurationIT.java` file
    - The tests pass in this scenario for Mac and Windows

**Comment by evelinec** [comment]
> ## Testing the application
> * [ ]  add hotspot for which configuration line to delete:
>   > To see whether the tests detect a failure, remove the configuration resetting line in the `setup()` method
> * [x]  add hotspots for `io_openliberty_guides_inventory_inMaintenance` and `META-INF/microprofile-config.properties`:
>   > The `testInitialServiceStatus()` test case reads the value of the `io_openliberty_guides_inventory_inMaintenance` configuration property in the file `META-INF/microprofile-config.properties`
>   > Because the `io_openliberty_guides_inventory_inMaintenance` configuration property is set to false by default

Regarding the first feedback, noticed that this section of the guide is to trigger user to further play around with the application/test that they learned in this guide on their own, thus, we do not state the instructions very specifically. This is by design of the guide. For this particular one, it's tricker than others.

**Comment by evelinec** [comment]
> * [ ]  On linux, the tests fail in this scenario (which it shouldn't):
>   
>   * when you manually change some configuration values in the `resources/CustomConfigSource.json`
>     (e.g. change `"io_openliberty_guides_inventory_inMaintenance":false` to `"io_openliberty_guides_inventory_inMaintenance":true`)
>     WITHOUT removing the configuration resetting line in the `setup()` method of the `ConfigurationIT.java` file
>   * The tests pass in this scenario for Mac and Windows

After some testing, turned out that setting the `CustomConfigSource` by change `"io_openliberty_guides_inventory_inMaintenance":false` to `"io_openliberty_guides_inventory_inMaintenance":true` do have an affect on the InventoryEndpointIT test, which failed, if this test is run first in the series of tests. On Linux, this is the case. The `InventoryEndpointIT` test is always run first: 

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.io.openliberty.guides.inventory.InventoryEndpointIT
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.925 s <<< FAILURE! - in it.io.openliberty.guides.inventory.InventoryEndpointIT
[ERROR] testSuite  Time elapsed: 4.839 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Incorrect response code from http://localhost:9080/ ==> expected: <200> but was: <503>
	at it.io.openliberty.guides.inventory.InventoryEndpointIT.assertResponse(InventoryEndpointIT.java:167)
	at it.io.openliberty.guides.inventory.InventoryEndpointIT.testHostRegistration(InventoryEndpointIT.java:74)
	at it.io.openliberty.guides.inventory.InventoryEndpointIT.testSuite(InventoryEndpointIT.java:63)

[INFO] Running it.io.openliberty.guides.config.ConfigurationIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.398 s - in it.io.openliberty.guides.config.ConfigurationIT
[INFO] Running it.io.openliberty.guides.system.SystemEndpointIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.21 s - in it.io.openliberty.guides.system.SystemEndpointIT
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   InventoryEndpointIT.testSuite:63->testHostRegistration:74->assertResponse:167 Incorrect response code from http://localhost:9080/ ==> expected: <200> but was: <503>
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[ERROR] Integration tests failed: There are test failures.
```

Whereas in Mac (only other environment I tried), has run the tests in a different order: 

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running it.io.openliberty.guides.config.ConfigurationTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.932 s - in it.io.openliberty.guides.config.ConfigurationTest
[INFO] Running it.io.openliberty.guides.system.SystemEndpointTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 s - in it.io.openliberty.guides.system.SystemEndpointTest
[INFO] Running it.io.openliberty.guides.inventory.InventoryEndpointTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.22 s - in it.io.openliberty.guides.inventory.InventoryEndpointTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
```

In this case, where the config properties was changed, but if the `ConfigurationIT` tests is run first, it'll reset the config properties to the default values, which will not fail the `InventoryEndpointIT` tests. 

This seems to be a Linux OS behaviour. 

As far as the user actions performed, all test case results on all platforms are as expected.

**Pull request merged**
