### PR TITLE
update error msg

### PR DESCRIPTION
**Pull request by TiagoF99**
- update error message in InventoryResource and update tests to reflect issue outlined here: https://github.com/OpenLiberty/guides-common/issues/243

### CODE REVIEW

**Comment by TiagoF99** [comment]
@AustinSeto Fixed your suggested changes

**Comment by TiagoF99** [comment]
@AustinSeto Addressed your comment.

**Comment by TiagoF99** [comment]
@AustinSeto Should be fixed now.

**Comment by DannyS03** [comment]
- Tested/verified on **qa**.

**Pull request merged**
